name: Build & Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Jar with Gradle
        uses: gradle/gradle-build-action@v3
        with:
          arguments: build -x test

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          IMAGE_SHA=ghcr.io/urfu-cakeshop/cake-shop-identity-service:${{ github.sha }}
          IMAGE_LATEST=ghcr.io/urfu-cakeshop/cake-shop-identity-service:latest

          docker build -t $IMAGE_SHA -t $IMAGE_LATEST .
          docker push $IMAGE_SHA
          docker push $IMAGE_LATEST