name: Build & Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Jar
        run: ./gradlew build -x test

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and Push image
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/cake-shop-identity-service:${{ github.sha }}
          docker build -t $IMAGE .
          docker push $IMAGE